spring:
  application:
    name: tacos
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=user
  data:
    rest:
      base-path: /api

# email properties

#tacocloud:
#  email:
#    host: imap.tacocloud.com
#    mailbox: INBOX
#    username: taco-in-flow
#    password: 1L0v3T4c0s
#    poll-rate: 10000