spring:
  application:
    name: tacos
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=user
  data:
    rest:
      base-path: /api
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

# email properties

#tacocloud:
#  email:
#    host: imap.tacocloud.com
#    mailbox: INBOX
#    username: taco-in-flow
#    password: 1L0v3T4c0s
#    poll-rate: 10000